iot:
  host: 192.168.1.177
  api:
    url: http://${iot.host}:8081/api/v4 # api默认地址 这个不要动 除非修改配置文件
    # admin public为默认认证的账号密码 生产环境建议修改  配置文件emqx_management.conf
    username: admin #认证账号 可以在Dashboard-->通用-->应用  新建app  AppId
    password: public #认证密码 可以在Dashboard-->通用-->应用  新建app  App秘钥
server:
  port: 9100
spring:
  redis:
    host: ${iot.host}
    port: 6379
    password: root
emqx:
  broker: tcp://${iot.host}:1883 #broker地址
  userName: root #授权账号 一定要授权的
  password: root #密码
  cleanSession: true #是否清除会话
  reconnect: true #是否断线重连
  timeout: 20 #连接超时时间
  keepAlive: 10 #心跳间隔